@host = https://localhost:7001

### Get all products
GET {{host}}/api/products
Accept: application/json

### Get product by id
GET {{host}}/api/products/1
Accept: application/json

### Get all brands
GET {{host}}/api/products/brands
Accept: application/json

### Get all types
GET {{host}}/api/products/types
Accept: application/json
